server:
  port: 8781

spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 47.103.42.10
    port: 6379
    timeout: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


feign:
  hystrix:
    enabled: true

